# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.cache/wt} [current_project]
set_property parent.project_path {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/ddc_minimum_phase_fir - new.coe}}
read_verilog -sv {
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/red_pitaya_pll.sv}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/red_pitaya_pwm.sv}
}
read_verilog {
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/axi_master.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/axi_slave.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/axi_wr_fifo.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/dpll_wrapper.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/red_pitaya_ams.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/red_pitaya_dfilt1.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/red_pitaya_hk.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/red_pitaya_ps.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/red_pitaya_scope.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/hdl/system_wrapper.v}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/imports/rtl/red_pitaya_top.v}
}
read_vhdl -library work {
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/first_order_IIR_highpass_filter.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/boxcar_4_pts_filter.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/boxcar_2_pts_filter.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/programmable_delay_line.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/adjustable_boxcar_filter_v2.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/N_times_clk_FIR_wrapper.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/ddc_frontend_lowpass_filter.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/quantizer.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/limiter.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/DDC_wideband_filters.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/simple_dualport_ram_with_init.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/FSM_addr_packed.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/IIR_LPF.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/resize_with_saturation.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/helper_functions.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/integrator_with_saturation.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/PLL_loop_filters_with_saturation.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/Status_LED_driver.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/addr_packed.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/adjustable_boxcar_filter.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/aux_data_mux.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/quadrature_dither_generator.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/dither_lockin.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/parallel_bus_register.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/dither_lockin_wrapper.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/triangular_frequency_counter.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/dual_type_frequency_counter.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/internal_vco.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/multiplexer_3to1_async.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/multiplexer_NbitsxMsignals_to_Nbits.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/mux_internal_vco.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/output_summing.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/parallel_bus_register_64_bits_or_less.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/simple_dualport_ram.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ram_data_logger.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/registers_read.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/residuals_monitor.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/system_identification_macc_behav.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/system_identification_with_dither2.vhd}
  {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/DigitalPLL/system_identification_vna_with_dither_wrapper.vhd}
}
add_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/system.bd}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/ip/system_axi_protocol_converter_0_0/system_axi_protocol_converter_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/ip/system_processing_system7_0/system_processing_system7_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/bd/system/system_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/clk_10MHz_sync/clk_10MHz_sync_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/constraints/fir_compiler_v7_2.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fir_compiler_minimumphase_N_times_clk/fir_compiler_minimumphase_N_times_clk_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/angle_CORDIC/angle_CORDIC.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/angle_CORDIC/angle_CORDIC_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_wide_mult/pll_wide_mult.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_wide_mult/pll_wide_mult_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/system_identification_outputgain_mult/system_identification_outputgain_mult_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/FIFO_addr_packed/FIFO_addr_packed_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/pll_32x32_mult_ii/pll_32x32_mult_ii_ooc.xdc}}]

read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/input_multiplier/input_multiplier.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/input_multiplier/input_multiplier_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/constrs_1/imports/sdc/red_pitaya.xdc}}
set_property used_in_implementation false [get_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/constrs_1/imports/sdc/red_pitaya.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top red_pitaya_top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef red_pitaya_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file red_pitaya_top_utilization_synth.rpt -pb red_pitaya_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
