# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci
# IP: The module: 'LO_DDS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LO_DDS'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci
# IP: The module: 'LO_DDS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'LO_DDS'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
