# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.cache/wt} [current_project]
set_property parent.project_path {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib work [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_ip -quiet {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci}}
set_property used_in_implementation false [get_files -all {{c:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top LO_DDS -part xc7z010clg400-1 -mode out_of_context

rename_ref -prefix_all LO_DDS_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LO_DDS.dcp
create_report "LO_DDS_synth_1_synth_report_utilization_0" "report_utilization -file LO_DDS_utilization_synth.rpt -pb LO_DDS_utilization_synth.pb"

if { [catch {
  write_verilog -force -mode synth_stub {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

add_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_stub.v}} -of_objects [get_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci}}]

add_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_stub.vhdl}} -of_objects [get_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci}}]

add_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_sim_netlist.v}} -of_objects [get_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci}}]

add_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_sim_netlist.vhdl}} -of_objects [get_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci}}]

add_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS.dcp}} -of_objects [get_files {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.srcs/sources_1/ip/LO_DDS/LO_DDS.xci}}]

if {[file isdir {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.ip_user_files/ip/LO_DDS}]} {
  catch { 
    file copy -force {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_sim_netlist.v}} {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.ip_user_files/ip/LO_DDS}
  }
}

if {[file isdir {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.ip_user_files/ip/LO_DDS}]} {
  catch { 
    file copy -force {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_sim_netlist.vhdl}} {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.ip_user_files/ip/LO_DDS}
  }
}

if {[file isdir {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.ip_user_files/ip/LO_DDS}]} {
  catch { 
    file copy -force {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_stub.v}} {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.ip_user_files/ip/LO_DDS}
  }
}

if {[file isdir {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.ip_user_files/ip/LO_DDS}]} {
  catch { 
    file copy -force {{C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.runs/LO_DDS_synth_1/LO_DDS_stub.vhdl}} {C:/Git/Frequency-comb-DPLL/Firmware Vivado Project/redpitaya.ip_user_files/ip/LO_DDS}
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
